version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: device_manager_user
      POSTGRES_PASSWORD: device_manager_password
      POSTGRES_DB: device_manager_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
  devicemanagerservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: devicemanagerservice
    hostname: devicemanagerservice
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_PROFILES: postgres
      DATABASE_USERNAME: device_manager_user
      DATABASE_PASSWORD: device_manager_password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      DATABASE_NAME: device_manager_db
      DATABASE_SCHEMA: device_manager